# Extract from PCAP to CSV

In [1]:
import os
from pathlib import Path

import pandas as pd

os.chdir(Path.cwd().parents[0])
print("Now in:", Path.cwd())

import warnings

warnings.filterwarnings("ignore")

Now in: C:\Users\stsax\OneDrive\Studium\9. Semester\Masterarbeit\Repository

In [2]:
dataPathCSV = str(Path.cwd()) + r"\data\csv" + "\\"
dataPathPCAP = str(Path.cwd()) + r"\data\pcap" + "\\"
picklePath = str(Path.cwd()) + r"\out\pickle_objects\processing_pipeline" + "\\"
plotPath = str(Path.cwd()) + r"\out\plots\tracker_analysis" + "\\"

In [3]:
import pickle

with open(picklePath + 'Processing Pipeline.pickle', 'rb') as f:
    AnalysisPipeline = pickle.load(f)

AnalysisPipeline.print(priority=True, flags=True)

AnalysisPipeline_part_1 = AnalysisPipeline[0]
AnalysisPipeline_part_2 = AnalysisPipeline
del AnalysisPipeline_part_2[0]

Processing Pipeline
	10 Pre Processing: Pre Processing
		10 Select and order columns
		15 Company ID and UUID
			10 Fill Company ID with None
			20 Fill UUID with None
			30 Replace Company IDs
			40 Replace Company UUIDs
		20 MS Data Processing
			10 Fill MS Data with empty String
			20 Length of MS Data
			30 Continuity Type
			40 Drop MS Data Column
		25 Service Data Processing
			10 Fill Service Data with empty String
			20 Length of Service Data
			30 Samsung Type
			40 Drop Service Data Column
		30 Fill Numeric NA with 0
		40 Fill String NA with None
		50 Broadcast
		60 Datetime conversion
		80 Order DataFrame
		90 Convert object type to string
	20 Dummy Processing: Dummy Processing
		30 Dummies Channel
		40 Dummies AD Type
		50 Dummies Company
		55 Dummies UUID
		70 Dummies PDU Type
		80 Dummies Continuity Type
		90 Dummies SmartTag Type
	30 Labeling: Labeling
		10 Labeling auto: Labeling auto
			Label Apple AirTag and Owner Device: Label Apple AirTag and nearby Owner Device
			Label Apple AirTag 2 and Owner Device: Label Apple AirTag 2 and nearby Owner Device
			Label Chipolo ONE and Owner Device: Label Chipolo ONE and nearby Owner Device
			Label Chipolo CARD [Apple] and Owner Device: Label Chipolo CARD [Apple] and nearby Owner Device
			Label 4Smarts SkyTag and Owner Device: Label 4Smarts SkyTag and nearby Owner Device
			Label 4Smarts SkyTag Card and Owner Device: Label 4Smarts SkyTag Card and nearby Owner Device
			Label KeySmart SmartCard and Owner Device: Label KeySmart SmartCard and nearby Owner Device
			Label Apple AirPod and Owner Device: Label Apple AirPod and nearby Owner Device
			Label Motorola MotoTag and Owner Device: Label Motorola MotoTag and nearby Owner Device
			Label Lifemate LifeTag and Owner Device: Label Lifemate LifeTag and nearby Owner Device
			Label Hama MGF and Owner Device: Label Hama MGF and nearby Owner Device
			Label Chipolo CARD [Google] and Owner Device: Label Chipolo CARD [Google] and nearby Owner Device
			Label Tile Mate and Owner Device: Label Tile Mate and nearby Owner Device
			Label Tile Slim and Owner Device: Label Tile Slim and nearby Owner Device
			Label Owner Device and Samsung SmartTag: Label Samsung SmartTag and nearby Owner Device
		20 Labeling manual: Labeling manual
			Label Apple iPhone: Label Apple iPhone
			Label Apple iPad: Label Apple iPad
			Label Apple AirPod: Label Apple AirPod
			Label Apple MacBook: Label Apple MacBook
			Label Apple AirTag: Label Apple AirTag
			Label Apple AirTag 2: Label Apple AirTag 2
			Label Chipolo ONE: Label Chipolo ONE
			Label 4Smarts SkyTag: Label 4Smarts SkyTag
			Label 4Smarts SkyTag Card: Label 4Smarts SkyTag Card
			Label KeySmart SmartCard: Label KeySmart SmartCard
			Label Chipolo CARD [Apple]: Label Chipolo CARD [Apple]
			Label Chipolo CARD [Google]: Label Chipolo CARD [Google]
			Label Chipolo POP [Apple]: Label Chipolo POP [Apple]
			Label Chipolo POP [Google]: Label Chipolo POP [Google]
			Label Samsung SmartTag: Label Samsung SmartTag
			Label Tile Mate: Label Tile Mate
			Label Tile Slim: Label Tile Slim
			Label Motorola MotoTag: Label Motorola MotoTag
			Label Lifemate LifeTag: Label Lifemate LifeTag
			Label Hama MGF: Label Hama MGF
			Label other Device: Label other Device
	40 States: States
		10 State Column
		20 States iDevices: States iDevices
			Continuity
			online: State online
			offline: State offline
		30 States Trackers: States Tracker
			lost: State lost
			nearby: State nearby
			unpaired: State unpaired
			searching: State searching
		Collapse State Column
	80 Modeling: Modeling
		0 Drop Column Continuity
		10 Drop Columns

In [4]:
with open(picklePath + 'Pre Processing.pickle', 'rb') as f:
    flag_preProcessing = pickle.load(f)

with open(picklePath + 'Modeling.pickle', 'rb') as f:
    flag_modeling = pickle.load(f)

with open(picklePath + 'Dummy Processing.pickle', 'rb') as f:
    flag_dummy = pickle.load(f)

with open(picklePath + 'State lost.pickle', 'rb') as f:
    flag_state_lost = pickle.load(f)

with open(picklePath + 'State unpaired.pickle', 'rb') as f:
    flag_state_unpaired = pickle.load(f)

with open(picklePath + 'State nearby.pickle', 'rb') as f:
    flag_state_nearby = pickle.load(f)

with open(picklePath + 'State searching.pickle', 'rb') as f:
    flag_state_searching = pickle.load(f)

with open(picklePath + 'State online.pickle', 'rb') as f:
    flag_state_online = pickle.load(f)

with open(picklePath + 'State offline.pickle', 'rb') as f:
    flag_state_offline = pickle.load(f)

with open(picklePath + 'States iDevices.pickle', 'rb') as f:
    flag_states_iDevices = pickle.load(f)

In [5]:
from data_processing.preprocessing_functions import filesToDataFrame

files = {r"other Device\other Device": [flag_preProcessing, flag_dummy, "Label other Device"],


        r"BLE Tracker\Apple Find My\Apple AirTag 2\Apple_AirTag_2_(nearby)": [flag_preProcessing,
                                                                               flag_dummy,
                                                                               "Label Apple AirTag 2 and nearby Owner Device",
                                                                               flag_state_nearby],

         r"BLE Tracker\Apple Find My\Apple AirTag 2\Apple_AirTag_2_(lost)": [flag_preProcessing,
                                                                             flag_dummy,
                                                                             "Label Apple AirTag 2",
                                                                             flag_state_lost],
         r"BLE Tracker\Apple Find My\Apple AirTag 2\Apple_AirTag_2_(unpaired)": [flag_preProcessing,
                                                                                 flag_dummy,
                                                                                 "Label Apple AirTag 2",
                                                                                 flag_state_unpaired],

         r"BLE Tracker\Apple Find My\Apple AirTag\Apple_AirTag_(nearby)": [flag_preProcessing,
                                                                           flag_dummy,
                                                                           "Label Apple AirTag and nearby Owner Device",
                                                                           flag_state_nearby],
         r"BLE Tracker\Apple Find My\Apple AirTag\Apple_AirTag_(lost)": [flag_preProcessing,
                                                                         flag_dummy,
                                                                         "Label Apple AirTag",
                                                                         flag_state_lost],
         r"BLE Tracker\Apple Find My\Apple AirTag\Apple_AirTag_(unpaired)": [flag_preProcessing,
                                                                             flag_dummy,
                                                                             "Label Apple AirTag",
                                                                             flag_state_unpaired],

         r"BLE Tracker\Apple Find My\Chipolo ONE\Chipolo_ONE_(nearby)": [flag_preProcessing,
                                                                         flag_dummy,
                                                                         "Label Chipolo ONE and nearby Owner Device",
                                                                         flag_state_nearby],
         r"BLE Tracker\Apple Find My\Chipolo ONE\Chipolo_ONE_(lost)": [flag_preProcessing, flag_dummy,
                                                                       "Label Chipolo ONE",
                                                                       flag_state_lost],
         r"BLE Tracker\Apple Find My\Chipolo ONE\Chipolo_ONE_(unpaired)": [flag_preProcessing,
                                                                           flag_dummy,
                                                                           "Label Chipolo ONE",
                                                                           flag_state_unpaired],

         r"BLE Tracker\Apple Find My\4Smarts SkyTag\4Smarts_SkyTag_(nearby)": [flag_preProcessing,
                                                                               flag_dummy,
                                                                               "Label 4Smarts SkyTag and nearby Owner Device",
                                                                               flag_state_nearby],
         r"BLE Tracker\Apple Find My\4Smarts SkyTag\4Smarts_SkyTag_(lost)": [flag_preProcessing,
                                                                             flag_dummy,
                                                                             "Label 4Smarts SkyTag",
                                                                             flag_state_lost],
         r"BLE Tracker\Apple Find My\4Smarts SkyTag\4Smarts_SkyTag_(unpaired)": [flag_preProcessing,
                                                                                 flag_dummy,
                                                                                 "Label 4Smarts SkyTag",
                                                                                 flag_state_unpaired],

         r"BLE Tracker\Apple Find My\KeySmart SmartCard\KeySmart_SmartCard_(nearby)": [flag_preProcessing,
                                                                                           flag_dummy,
                                                                                           "Label KeySmart SmartCard and nearby Owner Device",
                                                                                           flag_state_nearby],
         r"BLE Tracker\Apple Find My\KeySmart SmartCard\KeySmart_SmartCard_(lost)": [flag_preProcessing,
                                                                                         flag_dummy,
                                                                                         "Label KeySmart SmartCard",
                                                                                         flag_state_lost],
         r"BLE Tracker\Apple Find My\KeySmart SmartCard\KeySmart_SmartCard_(unpaired)": [flag_preProcessing,
                                                                                             flag_dummy,
                                                                                             "Label KeySmart SmartCard",
                                                                                             flag_state_unpaired],

         r"BLE Tracker\Apple Find My\Chipolo CARD\Chipolo_CARD_(nearby)_(Apple)": [flag_preProcessing,
                                                                                   flag_dummy,
                                                                                   "Label Chipolo CARD [Apple] and nearby Owner Device",
                                                                                   flag_state_nearby],
         r"BLE Tracker\Apple Find My\Chipolo CARD\Chipolo_CARD_(lost)_(Apple)": [flag_preProcessing, flag_dummy,
                                                                                 "Label Chipolo CARD [Apple]",
                                                                                 flag_state_lost],
         r"BLE Tracker\Apple Find My\Chipolo CARD\Chipolo_CARD_(unpaired)": [flag_preProcessing,
                                                                             flag_dummy,
                                                                             "Label Chipolo CARD [Apple]",
                                                                             flag_state_unpaired],

         r"BLE Tracker\Apple Find My\4Smarts SkyTag Card\4Smarts_SkyTag_Card_(nearby)": [flag_preProcessing,
                                                                                         flag_dummy,
                                                                                         "Label 4Smarts SkyTag Card and nearby Owner Device",
                                                                                         flag_state_nearby],
         r"BLE Tracker\Apple Find My\4Smarts SkyTag Card\4Smarts_SkyTag_Card_(lost)": [flag_preProcessing,
                                                                                       flag_dummy,
                                                                                       "Label 4Smarts SkyTag Card",
                                                                                       flag_state_lost],
         r"BLE Tracker\Apple Find My\4Smarts SkyTag Card\4Smarts_SkyTag_Card_(unpaired)": [flag_preProcessing,
                                                                                           flag_dummy,
                                                                                           "Label 4Smarts SkyTag Card",
                                                                                           flag_state_unpaired],

         r"BLE Tracker\Google Find My\Motorola MotoTag\Motorola_MotoTag_(nearby)": [flag_preProcessing,
                                                                                    flag_dummy,
                                                                                    "Label Motorola MotoTag and nearby Owner Device",
                                                                                    flag_state_nearby],

         r"BLE Tracker\Google Find My\Motorola MotoTag\Motorola_MotoTag_(lost)": [flag_preProcessing,
                                                                                  flag_dummy,
                                                                                  "Label Motorola MotoTag",
                                                                                  flag_state_lost],

         r"BLE Tracker\Google Find My\Motorola MotoTag\Motorola_MotoTag_(unpaired)": [flag_preProcessing,
                                                                                      flag_dummy,
                                                                                      "Label Motorola MotoTag",
                                                                                      flag_state_unpaired],

         r"BLE Tracker\Google Find My\Lifemate LifeTag\Lifemate_LifeTag_(nearby)": [flag_preProcessing,
                                                                                    flag_dummy,
                                                                                    "Label Lifemate LifeTag and nearby Owner Device",
                                                                                    flag_state_nearby],

         r"BLE Tracker\Google Find My\Lifemate LifeTag\Lifemate_LifeTag_(lost)": [flag_preProcessing,
                                                                                  flag_dummy,
                                                                                  "Label Lifemate LifeTag",
                                                                                  flag_state_lost],

         r"BLE Tracker\Google Find My\Lifemate LifeTag\Lifemate_LifeTag_(unpaired)": [flag_preProcessing,
                                                                                      flag_dummy,
                                                                                      "Label Lifemate LifeTag",
                                                                                      flag_state_unpaired],

         r"BLE Tracker\Google Find My\Hama MGF\Hama_MGF_(nearby)": [flag_preProcessing,
                                                                    flag_dummy,
                                                                    "Label Hama MGF and nearby Owner Device",
                                                                    flag_state_nearby],

         r"BLE Tracker\Google Find My\Hama MGF\Hama_MGF_(lost)": [flag_preProcessing,
                                                                  flag_dummy,
                                                                  "Label Hama MGF",
                                                                  flag_state_lost],

         r"BLE Tracker\Google Find My\Hama MGF\Hama_MGF_(unpaired)": [flag_preProcessing,
                                                                      flag_dummy,
                                                                      "Label Hama MGF",
                                                                      flag_state_unpaired],

         r"BLE Tracker\Google Find My\Chipolo CARD\Chipolo_CARD_(nearby)_(Google)": [flag_preProcessing,
                                                                                     flag_dummy,
                                                                                     "Label Chipolo CARD [Google] and nearby Owner Device",
                                                                                     flag_state_nearby],

         r"BLE Tracker\Google Find My\Chipolo CARD\Chipolo_CARD_(lost)_(Google)": [flag_preProcessing, flag_dummy,
                                                                                   "Label Chipolo CARD [Google]",
                                                                                   flag_state_lost],

         r"BLE Tracker\Google Find My\Chipolo CARD\Chipolo_CARD_(unpaired)": [flag_preProcessing,
                                                                              flag_dummy,
                                                                              "Label Chipolo CARD [Google]",
                                                                              flag_state_unpaired],

         r"BLE Tracker\Samsung SmartThings\Samsung SmartTag\Samsung_SmartTag_(nearby)": [flag_preProcessing,
                                                                                         flag_dummy,
                                                                                         "Label Samsung SmartTag and nearby Owner Device",
                                                                                         flag_state_nearby],
         r"BLE Tracker\Samsung SmartThings\Samsung SmartTag\Samsung_SmartTag_(lost)": [flag_preProcessing,
                                                                                       flag_dummy,
                                                                                       "Label Samsung SmartTag",
                                                                                       flag_state_lost],
         r"BLE Tracker\Samsung SmartThings\Samsung SmartTag\Samsung_SmartTag_(unpaired)": [flag_preProcessing,
                                                                                           flag_dummy,
                                                                                           "Label Samsung SmartTag",
                                                                                           flag_state_unpaired],
         r"BLE Tracker\Samsung SmartThings\Samsung SmartTag\Samsung_SmartTag_(searching)": [flag_preProcessing,
                                                                                            flag_dummy,
                                                                                            "Label Samsung SmartTag",
                                                                                            flag_state_searching],

         r"BLE Tracker\Tile\Tile Mate\Tile_Mate_(nearby)": [flag_preProcessing,
                                                            flag_dummy,
                                                            "Label Tile Mate and nearby Owner Device",
                                                            flag_state_nearby],
         r"BLE Tracker\Tile\Tile Mate\Tile_Mate_(lost)": [flag_preProcessing,
                                                          flag_dummy,
                                                          "Label Tile Mate",
                                                          flag_state_lost],
         r"BLE Tracker\Tile\Tile Mate\Tile_Mate_(unpaired)": [flag_preProcessing,
                                                              flag_dummy,
                                                              "Label Tile Mate",
                                                              flag_state_unpaired],
         r"BLE Tracker\Tile\Tile Mate\Tile_Mate_(searching)": [flag_preProcessing,
                                                               flag_dummy,
                                                               "Label Tile Mate",
                                                               flag_state_searching],

         r"BLE Tracker\Tile\Tile Slim\Tile_Slim_(nearby)": [flag_preProcessing,
                                                            flag_dummy,
                                                            "Label Tile Slim and nearby Owner Device",
                                                            flag_state_nearby],
         r"BLE Tracker\Tile\Tile Slim\Tile_Slim_(lost)": [flag_preProcessing,
                                                          flag_dummy,
                                                          "Label Tile Slim",
                                                          flag_state_lost],
         r"BLE Tracker\Tile\Tile Slim\Tile_Slim_(unpaired)": [flag_preProcessing,
                                                              flag_dummy,
                                                              "Label Tile Slim",
                                                              flag_state_unpaired],

         r"Apple iDevices\Apple iPhone\Apple_iPhone_(online)": [flag_preProcessing,
                                                                flag_dummy,
                                                                "Label Apple iPhone",
                                                                flag_state_online],
         r"Apple iDevices\Apple iPhone\Apple_iPhone_(offline)": [flag_preProcessing,
                                                                 flag_dummy,
                                                                 "Label Apple iPhone",
                                                                 flag_state_offline],

         r"Apple iDevices\Apple iPad\Apple_iPad_(online)": [flag_preProcessing,
                                                                flag_dummy,
                                                                "Label Apple iPad",
                                                                flag_state_online],
         r"Apple iDevices\Apple iPad\Apple_iPad_(offline)": [flag_preProcessing,
                                                                 flag_dummy,
                                                                 "Label Apple iPad",
                                                                 flag_state_offline],

         r"Apple iDevices\Apple MacBook\Apple_MacBook_(online)": [flag_preProcessing,
                                                                  flag_dummy,
                                                                  "Label Apple MacBook",
                                                                  flag_state_online],
         r"Apple iDevices\Apple MacBook\Apple_MacBook_(offline)": [flag_preProcessing,
                                                                   flag_dummy,
                                                                   "Label Apple MacBook",
                                                                   flag_state_offline],

         r"Apple iDevices\Apple AirPod\Apple_AirPod_(nearby)": [flag_preProcessing,
                                                                flag_dummy,
                                                                "Label Apple AirPod and nearby Owner Device",
                                                                flag_states_iDevices,
                                                                flag_state_nearby],
         r"Apple iDevices\Apple AirPod\Apple_AirPod_(lost)": [flag_preProcessing,
                                                              flag_dummy,
                                                              "Label Apple AirPod",
                                                              flag_states_iDevices,
                                                              flag_state_lost],


         }


data = filesToDataFrame(files,
                        dropLabels=['Owner Device', 'Apple iPhone (offline)', 'Apple iPhone (online)',
                                           'Apple iPad (offline)', 'Apple iPad (online)', 'Apple AirPod (lost)',
                                           'Apple AirPod (nearby)', 'Apple iPad CT 09 (offline)',
                                           'Apple AirPod CT 09 (nearby)', 'Apple MacBook (offline)',
                                           'Apple MacBook (online)'],

                        pipeline_part_1=AnalysisPipeline_part_1,
                        pipeline_part_2=AnalysisPipeline_part_2,
                        picklePath=picklePath,
                        dataPathCSV=dataPathCSV,
                        dataPathPCAP=dataPathPCAP)

In [6]:
data.to_csv(dataPathCSV + r"Processed Files\labeled_and_aggregated_data.csv", encoding='utf-8', index=False, sep=',')

In [7]:
data.to_parquet(dataPathCSV + r"Processed Files\labeled_and_aggregated_data.parquet",
                engine="pyarrow",
                compression="snappy",
                index=False)

In [8]:
data = pd.read_parquet(dataPathCSV + r"Processed Files\labeled_and_aggregated_data.parquet")

In [9]:
from data_processing.LabelLut import LABEL_LUT_PROD


data = data[data['Source'] != '']
data = data.sort_values(["Label", "File", "Source", "Time"]).copy()
data['Label'] = data['Label'].replace(to_replace=LABEL_LUT_PROD)

In [10]:
data.info()

<class 'pandas.DataFrame'>
Index: 10905992 entries, 305632 to 9107938
Data columns (total 7 columns):
 #   Column    Dtype
---  ------    -----
 0   Time      float64
 1   Source    str
 2   Channel   int64
 3   RSSI      int64
 4   Hex Data  str
 5   Label     string
 6   File      str
dtypes: float64(1), int64(2), str(3), string(1)
memory usage: 2.2 GB

In [11]:
size_per_label = data.groupby("Label", group_keys=False).size().reset_index().rename(columns={0: 'Count'})
size_per_label = size_per_label[size_per_label['Count'] >= 20_000]

size_per_label

                                   Label    Count
0                           Apple Device  6316980
1         Apple Find My Device (offline)   182397
2          Apple Find My Device (online)   189946
3           Apple Find My Tracker (lost)   426014
4         Apple Find My Tracker (nearby)   354518
5       Apple Find My Tracker (unpaired)   697616
6     Apple Find My Tracker Gen 2 (lost)   129302
7   Apple Find My Tracker Gen 2 (nearby)   128193
8          Google Find My Tracker (lost)   197715
9        Google Find My Tracker (nearby)   201810
10     Google Find My Tracker (unpaired)    40912
11                          Other Device  1776634
12    Samsung SmartThings Tracker (lost)    32829
13  Samsung SmartThings Tracker (nearby)    24943
16                   Tile Tracker (lost)    97077
17                 Tile Tracker (nearby)    96419

In [12]:
data = data.merge(size_per_label, on="Label", how="inner").reset_index(drop=True)
data.drop('Count', axis=1, inplace=True)
data

,Time,Source,Channel,RSSI,Hex Data,Label,File
0,1.712965e+09,6580254984E9,37,44,D6BE898E4025E984492580651EFF4C001219204CA22FB7...,Apple Find My Tracker (lost),BLE Tracker\Apple Find My\4Smarts SkyTag\4Smar...
1,1.712943e+09,DA80254984E9,37,44,D6BE898E4025E984492580DA1EFF4C0012192074222EB7...,Apple Find My Tracker (lost),BLE Tracker\Apple Find My\4Smarts SkyTag\4Smar...
2,1.712943e+09,DA80254984E9,38,44,D6BE898E4025E984492580DA1EFF4C0012192074222EB7...,Apple Find My Tracker (lost),BLE Tracker\Apple Find My\4Smarts SkyTag\4Smar...
3,1.712943e+09,DA80254984E9,39,47,D6BE898E4025E984492580DA1EFF4C0012192074222EB7...,Apple Find My Tracker (lost),BLE Tracker\Apple Find My\4Smarts SkyTag\4Smar...
4,1.712943e+09,DA80254984E9,37,45,D6BE898E4025E984492580DA1EFF4C0012192074222EB7...,Apple Find My Tracker (lost),BLE Tracker\Apple Find My\4Smarts SkyTag\4Smar...
...,...,...,...,...,...,...,...
10893300,1.713890e+09,FF9012A713FC,37,40,D6BE898E4085FC13A71290FF41078F5B27F3D9F384542A...,Other Device,other Device\other Device
10893301,1.713889e+09,FFA2238F0C67,37,44,D6BE898EC30C670C8F23A2FFF92B8A435B6E707E3B,Other Device,other Device\other Device
10893302,1.713889e+09,FFB1BC2E416D,39,49,D6BE898EC30C6D412EBCB1FF36494CC38F48ECADC7,Other Device,other Device\other Device
10893303,1.713887e+09,FFE3A36756F9,39,50,D6BE898E6011F95667A3E3FF0A8E40AF473D1CCB81075A...,Other Device,other Device\other Device
10893304,1.713890e+09,FFEDCF5BD865,38,42,D6BE898E066E65D85BCFEDFF0327D3BA63C6DD885167C7...,Other Device,other Device\other Device

In [13]:
from data_processing.preprocessing_functions import split_train_val_test

train, val, test = split_train_val_test(data, train_frac=0.8, val_frac=0.1, test_frac=0.1, file_col='File', time_col='Time')

In [14]:
train = train.sort_values(["Label", "File", "Source", "Time"]).reset_index(drop=True)
val = val.sort_values(["Label", "File", "Source", "Time"]).reset_index(drop=True)
test = test.sort_values(["Label", "File", "Source", "Time"]).reset_index(drop=True)

In [15]:
train.to_parquet(dataPathCSV + r"Processed Files\labeled_and_aggregated_data_train.parquet",
                engine="pyarrow",
                compression="snappy",
                index=False)

val.to_parquet(dataPathCSV + r"Processed Files\labeled_and_aggregated_data_validation.parquet",
                engine="pyarrow",
                compression="snappy",
                index=False)


test.to_parquet(dataPathCSV + r"Processed Files\labeled_and_aggregated_data_test.parquet",
                engine="pyarrow",
                compression="snappy",
                index=False)